Mvc5.Knowleadge/Areas/RoutesHighAttribute/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc5.Knowleadge.Areas.RoutesHighAttribute.Controllers
{
    //[RouteArea("RoutesHighAttribute")]
    //[RoutePrefix("Admin")]
    public class AdminController : Controller
    {
        // GET: RoutesHighAttribute/Admin
        //[Route("TestAction")]
        public ActionResult Index()
        {
            ViewBag.Controller = "Admin";
            ViewBag.Action = "Index";
            return View("ActionName");
        }


        public ActionResult CustomVariable(string id)
        {
            ViewBag.Controller = "Home";
            ViewBag.Action = "CustomVariable";
            ViewBag.CustomVariable = id;
            return View("ActionName");
        }
    }
}

Mvc5.Knowleadge/Areas/RoutesHighAttribute/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc5.Knowleadge.Areas.RoutesHighAttribute.Controllers
{
    [RouteArea("RoutesHighAttribute")]
    [RoutePrefix("User")]
    public class CustomerController : Controller
    {
        // GET: RoutesHighAttribute/Customer
        [Route("Test")]
        public ActionResult Index()
        {
            ViewBag.Controller = "Customer";
            ViewBag.Action = "Index";
            return View("ActionName");
        }

        public ActionResult List()
        {
            ViewBag.Controller = "Customer";
            ViewBag.Action = "List";
            return View("ActionName");
        }

    }
}

Mvc5.Knowleadge/Areas/RoutesHighAttribute/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc5.Knowleadge.Areas.RoutesHighAttribute.Controllers
{
    public class HomeController : Controller
    {
        // GET: RoutesHighAttribute/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Mvc5.Knowleadge/Areas/RoutesHighAttribute/Controllers/LegacyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc5.Knowleadge.Areas.RoutesHighAttribute.Controllers
{
    public class LegacyController : Controller
    {
        // GET: RoutesHighAttribute/Legacy
        public ActionResult GetLegacyURL(string legacyURL)
        {
            return View((object)legacyURL);
        }
    }
}

Mvc5.Knowleadge/Areas/UrlsAndRoutes/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc5.Knowleadge.Areas.UrlsAndRoutes.Controllers
{
    [RoutePrefix("Users")]
    public class CustomerController : Controller
    {
        // GET: Home
        [Route("Test")]
        public ActionResult Index()
        {
            ViewBag.Controller = "Customer";
            ViewBag.Action = "Index";
            return View("ActionName");
        }

        //[Route("Users/Add/{user}/{int:id}")]--巨大错误
        [Route("Users/Add/{user}/{id:int}")]
        public string Create(string user, int id)
        {
            return $"创建动作 - 用户:{user},ID:{id}";
        }

        [Route("Users/Add/{user}/{passowrd}")]
        public string ChangePass(string user, string password)
        {
            return $"改变密码动作 - User:{user},Passowrd:{password}";
        }

        [Route("Users/Add/{user}/{passowrd:alpha:length(6)}")]
        public string ChangePassWord(string user, string password)
        {
            return $"改变密码动作 - User:{user},Passowrd:{password}";
        }

        public ActionResult List()
        {
            ViewBag.Controller = "Customer";
            ViewBag.Action = "List";
            return View("ActionName");
        }
    }
}

Mvc5.Knowleadge/Areas/UrlsAndRoutes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc5.Knowleadge.Areas.UrlsAndRoutes.Controllers
{
    public class HomeController : Controller
    {
        // GET: UrlsAndRoutes/Home
        public ActionResult Index()
        {
            ViewBag.Controller = "Home";
            ViewBag.Action = "Index";
            ViewBag.CustomVariable = RouteData.Values["id"];
            return View("ActionName");
        }

        public ActionResult CustomVariable(string id)
        {
            ViewBag.Controller = "Home";
            ViewBag.Action = "CustomVariable";
            ViewBag.CustomVariable = id;
            return View("ActionName");
        }


        public ActionResult CustomVariableOptional(string id)
        {
            ViewBag.Controller = "Home";
            ViewBag.Action = "CustomVariableOptional";
            ViewBag.CustomVariable = id ?? "没有id值";
            return View("ActionName");
        }
    }
}

Mvc5.Knowleadge/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc5.Knowleadge.Controllers
{
    [RoutePrefix("Users")]
    public class CustomerController : Controller
    {
        // GET: Home
        [Route("Test")]
        public ActionResult Index()
        {
            ViewBag.Controller = "Customer";
            ViewBag.Action = "Index";
            return View("ActionName");
        }

        [Route("Users/Add/{user}/{int:id}")]
        public string Create(string user, int id)
        {
            return $"创建动作 - 用户:{user},ID:{id}";
        }

        [Route("Users/Add/{user}/{passowrd}")]
        public string ChangePass(string user, string password)
        {
            return $"改变密码动作 - User:{user},Passowrd:{password}";
        }

        [Route("Users/Add/{user}/{passowrd:alpha:length(6)}")]
        public string ChangePassWord(string user, string password)
        {
            return $"改变密码动作 - User:{user},Passowrd:{password}";
        }

        public ActionResult List()
        {
            ViewBag.Controller = "Customer";
            ViewBag.Action = "List";
            return View("ActionName");
        }
    }
}

Mvc5.Knowleadge/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc5.Knowleadge.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.Controller = "Home";
            ViewBag.Action = "Index";
            ViewBag.CustomVariable = RouteData.Values["id"];
            return View("ActionName");
        }

        public ActionResult CustomVariable(string id)
        {
            ViewBag.Controller = "Home";
            ViewBag.Action = "Index";
            ViewBag.CustomVariable = id;
            return View("ActionName");
        }


        public ActionResult CustomVariableOptional(string id)
        {
            ViewBag.Controller = "Home";
            ViewBag.Action = "Index";
            ViewBag.CustomVariable = id ?? "没有id值";
            return View("ActionName");
        }
    }
}

Mvc5.Knowleadge/Areas/RoutesHighAttribute/Views/Home/Index.cshtml
@{
    ViewBag.Title = "高级路由特性";
}

<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3" id="id_scroll_spy">
    <ul class="nav nav-pills nav-stacked" id="id-affix">
        <li class="nav-link active"><a href="#modaldiv">16.1.项目初始化</a></li>
        <li class="nav-link"><a href="#typeaheaddiv">16.2.在视图中显示URL</a></li>
        <li class="nav-link"><a href="#spydiv">16.3.定制路由系统</a></li>
        <li class="nav-link"><a href="#tabdiv">16.4.使用区域</a></li>
        <li class="nav-link"><a href="#paneldiv">16.5.对磁盘文件使用路由</a></li>
        <li class="nav-link"><a href="#carouseldiv">16.6.绕过路由系统</a></li>
        <li class="nav-link"><a href="#dropmenudiv">16.7.最佳的URL方案</a></li>
    </ul>
</div>
<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
    <div class="jumbotron">
        <h3>Chapter16：高级路由特性</h3>
    </div>
    <div class="form-horizontal">
        <div id="modaldiv" class="form-group col-sm-12">
            <h4>16.1.1 初始化路由</h4>
            <p class="text-content">
                在新建的项目中,初始化 RoutesHighAttributeAreaRegistration类文件
            </p>
            <pre class="prettyprint linenums" style="margin-bottom: 2px;">
            @{
                var path= Server.MapPath("~/Areas");
                var data = File.ReadAllText(path+ @"/file/16.1.1InitRoutes.txt");
                foreach (var item in data)
                {
                    @item
                }
            }</pre>
            <h4>16.1.2 为项目和测试项目添加NuGet包</h4>
            <pre class="prettyprint linenums" style="margin-bottom: 2px;">Install-package Microsoft.AspNet.Web.Optimization -projectname Mvc5.Knowleadge
Install-package Microsoft.AspNet.Mvc -projectname Mvc5.Knowleadge.Tests</pre>
        </div>

        <div id="typeaheaddiv" class="form-group col-sm-12">
            <h4>16.2.1 用路由系统生成URL</h4>
            <pre class="prettyprint linenums" style="margin-bottom:2px">context.MapRoute("NewRoute", "App/Do{action}", new { controller = "Admin"});</pre>
            <p class="text-content">
                通过修改路由方案，在Html.ActionLink辅助器方法的中会显示URL实际生成的效果，测试链接：
                @*@Html.ActionLink("路由初始化", "Index", "Admin", new { area = "RoutesHighAttribute" }, null) <br />*@
                @Html.ActionLink("生成URL", "Index", "Admin")
            </p>
            <br />
            <h4>16.2.2 以其他控制器为目标</h4>
            <p class="text-content">
                @*@Html.ActionLink("指定控制器", "CustomVariable", "Home", new { area = "RoutesHighAttribute" }, null) <br />*@
                @Html.ActionLink("指定控制器", "CustomVariable")
            </p>
            <p class="text-content">
                @*@Html.ActionLink("指定控制器2", "Index", "Customer", new { area = "RoutesHighAttribute" }, null) <br />*@
                @Html.ActionLink("指定控制器2", "Index", "Customer")
            </p>

            <h4>16.2.3 以其他控制器为目标</h4>
            <p class="text-content">
                @Html.ActionLink("设定参数", "CustomVariable", "Admin", new { id = "Hello" }, null)
            </p>
            <p class="text-content">
                @Html.ActionLink("设定参数", "CustomVariable", new { id = "Hello" })
            </p>

            <h4>16.2.4 添加标签属性</h4>
            <p class="text-content">
                @Html.ActionLink("设定参数", "CustomVariable", new { id = "Hello" }, new { id = "myAnchorID", @class = "myCSSClass" })
            </p>
            <p class="text-content">
                @Html.ActionLink("设定参数", "CustomVariable", "Home", "https", "myserver.cloudwhales.com", "myFragementName"
               , new { id = "Hello" }, new { id = "myAnchorID", @class = "myCSSClass" })
            </p>
        </div>

        <div id="spydiv" class="form-group col-sm-12">
            <h4>16.3.1 创建自定义的RouteBase实现</h4>
            <p class="text-content">
                @Html.ActionLink("测试定制路入站URL", "GetLegacyURL", "Legacy")
            </p>
            <p class="text-content">
                @Html.ActionLink("测试定制路由出站URL", "GetLegacyURL", "Legacy", new { area = "RoutesHighAttribute", legacyURL = "~/articles/Windows_3.1_Overview.html" }, null)
            </p>
            <h4>16.3.2 创建自定义路由处理程序</h4>
            <p class="text-content">
                @Html.ActionLink("路由处理程序", "GetLegacyURL", "Legacy", new { area = "" }, null)
            </p>
        </div>

        <div id="tabdiv" class="form-group col-sm-12">
            <h4>16.5对磁盘文件进行路由请求</h4>
            <p class="text-content">
                <a href="~/Areas/file/StaticContent.html">对磁盘路由请求</a>
            </p>
            <p class="text-content">
                @Html.ActionLink("对磁盘路由请求","List", "Customer")
            </p>
        </div>

        <div id="paneldiv" class="form-group col-sm-12">
            <label for="" class="col-sm-2 control-label">绕过路由系统:</label>
            <div class="col-sm-10">
            </div>
        </div>

        <div id="carouseldiv" class="form-group col-sm-12">
            <label for="" class="col-sm-2 control-label">最佳的URL方案:</label>
            <div class="col-sm-10">
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Scripts/prettify.js"></script>
    <script>
        $(function () {
            var $window = $(window);
            // make code pretty
            window.prettyPrint && prettyPrint();
            // 可将 data-spy="affix" data-offset-top="128" 去掉并使用这个JS
            $("#id-affix").affix({
                offset: { top: 128 }
            });
        })
    </script>
}

Mvc5.Knowleadge/Areas/RoutesHighAttribute/Views/Legacy/GetLegacyURL.cshtml
@model string 
@{
    ViewBag.Title = "GetLegacyURL";
}

<h2>测试定制路由</h2>
请求的URL是：@Model

Mvc5.Knowleadge/Areas/RoutesHighAttribute/Views/Shared/ActionName.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>控制器名称：@ViewBag.Controller</div>
    <div>动作名称：@ViewBag.Action</div>
    <div>查询变量：@ViewBag.CustomVariable</div>
    <div>@Html.ActionLink("这是一个出站URL", "CustomVariable", new { id = "Hello" })</div>
    <div>@Html.ActionLink("这是一个出站URL", "CustomVariable")</div>
</body>
</html>

Mvc5.Knowleadge/Areas/RoutesHighAttribute/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Chapter16高级路由特性</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/prettify.css"/>
    @*<script src="~/Scripts/modernizr-2.8.3.js"></script>*@
</head>
<body data-spy="scroll" data-target="#id_scroll_spy">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("高级路由特性", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("路由特性", "Index", "Home", new { area = "UrlsAndRoutes" })</li>
                    <li>@Html.ActionLink("控制器相关", "Index", "Home", new { area = "UrlsAndRoutes" })</li>
                    <li>@Html.ActionLink("视图辅助器", "Index", "Home", new { area = "UrlsAndRoutes" })</li>
                    <li>@Html.ActionLink("模型与NuGet", "Index", "Home", new { area = "UrlsAndRoutes" })</li>
                </ul>
            </div>
        </div>
    </div>

    <main>
        <div class="container">
            <div class="row">
                @RenderBody()
            </div>
        </div>
        <hr />
    </main>
    <footer class="text-center">
        <p>&copy; @DateTime.Now.Year - 高级路由特性</p>
    </footer>

    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Mvc5.Knowleadge/Views/Home/Index.cshtml
@{
    ViewBag.Title = "知识章节";
}

<h2>目录</h2>
<div>
    <ul>
        <li>@Html.ActionLink("第15章 URL路由", "Index", "Home", new { area = "UrlsAndRoutes" }, null)</li>
        <li>@Html.ActionLink("第16章 高级路由特性", "Index", "Home", new { area = "RoutesHighAttribute" }, null)</li>
        <li>@Html.ActionLink("定制路由入站", "GetLegacyURL","Legacy",new { area=""},null)</li>
        <li>@Html.ActionLink("定制路由出站", "GetLegacyURL", new{legacyURL="~/articles/Windows_3.1_Overview.html" });</li>
    </ul>
</div>

Mvc5.Knowleadge/Views/Shared/GetLegacyURL.cshtml
@model string 
@{
    ViewBag.Title = "GetLegacyURL";
}

<h2>测试定制路由</h2>
请求的URL是：@Model