SportsStore.WebUI/Areas/BackendAdmin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Concrete;
using SportsStore.Shared.Entities;
using SportsStore.Domain.Abstract;

namespace SportsStore.WebUI.Areas.BackendAdmin.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private IProductRepository repository;

        public ProductsController(IProductRepository repository)
        {
            this.repository = repository;
        }

        // GET: BackendAdmin/Products
        public ViewResult Index()
        {
            return View(repository.Products);
        }

        public FileContentResult GetImage(int productId)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                return File(product.ImageData, product.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        // GET: BackendAdmin/Products/Details/5
        public ViewResult Details(int? id)
        {
            Product product = repository.Products.FirstOrDefault(x => x.ProductID == id);
            return View(product);
        }

        // GET: BackendAdmin/Products/Create
        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        // GET: BackendAdmin/Products/Edit/5
        public ViewResult Edit(int productID)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productID);
            return View(product);
        }

        // POST: BackendAdmin/Products/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性。有关
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,Name,Description,Price,Category")] Product product,HttpPostedFileBase image=null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }
                //db.Entry(product).State = EntityState.Modified;
                repository.SaveProduct(product);
                TempData["message"] = $"{product.Name}已更新";
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // POST: BackendAdmin/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int productID)
        {
            Product deleteProduct = repository.DeleteProduct(productID);
            if (deleteProduct != null)
            {
                TempData["message"] = $"{deleteProduct.Name}已经被删除";
            }
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SportsStore.WebUI/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;

namespace SportsStore.WebUI.Controllers
{
    public class MenuController : Controller
    {
        private readonly IProductRepository repository;

        public MenuController(IProductRepository repository)
        {
            this.repository = repository;
        }

        // GET: MenuNav
        public PartialViewResult Index(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            //string viewName = horizontalLayout ? "MenuHorizontal" : "Menu";
            //return PartialView(viewName, categories);
            return PartialView("IndexMenuFlex", categories);
        }
    }
}

SportsStore.WebUI/Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Shared.DataInterface;
using SportsStore.Shared.Entities;
using SportsStore.Shared.ViewModel;

namespace SportsStore.WebUI.Controllers
{
    public class ShopCartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;

        public ShopCartController(IProductRepository repository, IOrderProcessor orderProcessor)
        {
            this.repository = repository;
            this.orderProcessor = orderProcessor;
        }

        public RedirectToRouteResult AddToShopCart(ShopCart shopCart, int productID, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productID);
            if (product != null)
            {
                shopCart.AddItemProduct(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFormShopCart(ShopCart shopCart, int productID, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productID);
            if (product != null)
            {
                shopCart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        //private ShopCart GetShopCart()
        //{
        //    ShopCart shopCart = (ShopCart)Session["ShopCart"];
        //    if (shopCart == null)
        //    {
        //        shopCart = new ShopCart();
        //        Session["ShopCart"] = shopCart;
        //    }
        //    return shopCart;
        //}

        // GET: ShopCart
        public ViewResult Index(ShopCart shopCart, string returnUrl)
        {
            return View(new ShopCartIndexViewModel
            {
                ShopCart = shopCart,
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult ShopCartSummary(ShopCart shopCart)
        {
            return PartialView(shopCart);
        }

        public ViewResult CheckOut()
        {
            return View(new ShoppingDetails());
        }

        [HttpPost]
        public ViewResult CheckOut(ShopCart shopCart,ShoppingDetails details)
        {
            if (shopCart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "您的购物车为空!");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(shopCart, details);
                shopCart.Clear();
                return View("Completed");
            }
            else
            {
                return View(details);
            }
        }
    }
}

SportsStore.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/jquery.mobile-1.4.5.min.css" />
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>运动商城</h3>
            @Html.Action("Index", "Menu")
        </div>
        <div data-role="content">
            <ul data-role="listview" data-dividertheme="b" data-inset="false">
                @RenderBody()
            </ul>
        </div>
    </div>

    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/jquery.mobile-1.4.5.min.js"></script>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 高光电商</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    @*<script src="~/Scripts/modernizr-2.8.3.js"></script>*@
    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left: 15px
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand navbar-inverse">
                    <span class="hidden-xs">运动商城</span>
                    <span class="visible-xs">运动</span>
                    <span class="visible-xs">商城</span>
                    @Html.Action("ShopCartSummary", "ShopCart")
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="visible-xs">
        @Html.Action("Index", "Menu", new { horizontalLayout = true })
    </div>
    <div class="container body-content">
        <div class="col-sm-3 hidden-xs">
            @Html.Action("Index", "Menu")
        </div>
        <div class="col-sm-9 col-xs-12">
            @RenderBody()
        </div>
        <hr />
    </div>

    <footer class="text-center">
        <p>&copy; @DateTime.Now.Year -高光运动-LINE SHOP @Html.ActionLink("Admin", "Index", "Products", new { area = "BackendAdmin" }, null)</p>
    </footer>

    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>